on:
  push:
    branches:
      - master
name: Deploy Extension
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x # 配置Node环境
        uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: '10.x'

      - name: Setup
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm install -g vsce
          npm run release
